model: "gpt2" # model name
APP:
    backend_url: "0.0.0.0" # backend url, set it to 0.0.0.0 to make it accessible from outside
    backend_port: 5050 # backend port
    backend_access: "localhost" # backend access from frontend / could be different in case backend server is different
